name: Release
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  build:
    name: Build and Lint
    uses: ./.github/workflows/development.yml
